### ISSUE TITLE
Sometimes Item.Recurrence is null

### ISSUE THREAD

**Issue by marcoancona** [gautamsi/ews-javascript-api#134]
I know a problem with Recurrence was address recently. I realised that still sometimes `Item.Recurrence` is null, even though `Item.IsRecurring` is true.
The following CalendarItem is a case when such happens:

```js
CalendarItem: {
  __prefix: 't',
  __type: 'CalendarItem',
  ItemId: {
    __prefix: 't',
    __type: 'ItemId',
    Id: 'AAMkAGYwA=',
    ChangeKey: 'DwAAABYAAAAZInWUlV8'
  },
  Subject: 'Invito aggiornato: stand-up meeting',
  Sensitivity: 'Normal',
  Body: {
    __prefix: 't',
    __type: 'Body',
    BodyType: 'HTML',
    Body: 'Some HTML'
  },
  DateTimeReceived: '2015-10-22T17:14:34Z',
  Importance: 'Normal',
  ReminderIsSet: 'false',
  ReminderMinutesBeforeStart: '0',
  EffectiveRights: {
    __prefix: 't',
    __type: 'EffectiveRights',
    CreateAssociated: 'false',
    CreateContents: 'false',
    CreateHierarchy: 'false',
    Delete: 'true',
    Modify: 'true',
    Read: 'true'
  },
  LastModifiedTime: '2016-09-26T21:33:20Z',
  Start: '2015-10-26T08:30:00Z',
  End: '2015-10-26T08:45:00Z',
  IsAllDayEvent: 'false',
  Location: 'Office area',
  IsRecurring: 'true',
  CalendarItemType: 'RecurringMaster',
  MyResponseType: 'Accept',
  Organizer: {
    __prefix: 't',
    __type: 'Organizer',
    Mailbox: {
      __prefix: 't',
      __type: 'Mailbox',
      Name: 'amail@mail.com',
      EmailAddress: 'amail@mail.com',
      RoutingType: 'SMTP'
    }
  },
  RequiredAttendees: {
    __prefix: 't',
    __type: 'RequiredAttendees',
    Attendee: [{
      __prefix: 't',
      __type: 'Attendee',
      {
        __prefix: 't',
        __type: 'Mailbox',
        Name: 'amail@mail.com',
        EmailAddress: 'amail@mail.com',
        RoutingType: 'SMTP'
      },
      ResponseType: 'Unknown'
    }, {
      __prefix: 't',
      __type: 'Attendee',
      Mailbox: {
        __prefix: 't',
        __type: 'Mailbox',
        Name: 'Second User',
        EmailAddress: 'asd@gmail.com',
        RoutingType: 'SMTP'
      },
      ResponseType: 'Unknown'
    }]
  },
  TimeZone: 'Europe/Zurich',
  AppointmentState: '3',
  Recurrence: {
    __prefix: 't',
    __type: 'Recurrence',
    WeeklyRecurrence: {
      __prefix: 't',
      __type: 'WeeklyRecurrence',
      Interval: '1',
      DaysOfWeek: 'Monday Tuesday Wednesday Thursday Friday'
    },
    EndDateRecurrence: {
      __prefix: 't',
      __type: 'EndDateRecurrence',
      StartDate: '2015-10-26+01:00',
      EndDate: '2016-02-24+01:00'
    }
  }
}
```

**Comment by marcoancona** [comment]
Here is another Recurrence response that leads to null `Item.Response` (I omit the rest of the CalendarItem for clarify):

```
Recurrence: {
  __prefix: 't',
  __type: 'Recurrence',
  WeeklyRecurrence: {
    __prefix: 't',
    __type: 'WeeklyRecurrence',
    Interval: '1',
    DaysOfWeek: 'Thursday'
  },
  EndDateRecurrence: {
    __prefix: 't',
    __type: 'EndDateRecurrence',
    StartDate: '2016-09-01+02:00',
    EndDate: '2016-09-29+02:00'
  }
}
```

**Comment by gautamsi** [comment]
will be fixed in next release. only Weekly Recurrence is affected.

**Comment by marcoancona** [comment]
Thanks

**Comment by marcoancona** [comment]
Which is the recommended way to get the type of pattern for an `item.Recurrence` ?
I can use eg. `item.Recurrence.constructor.name === 'WeeklyRecurrence'` but seems quite dirty to me.

**Comment by gautamsi** [comment]
let me push that code to GitHub, you can `gulp build` for this.

**Comment by marcoancona** [comment]
Oh, my question was more general not related to this issue. If I want to parse the Recurrence object (ie. to map it into a iCalendar RRULE) I need a way to know what kind of pattern the recurrence has.

**Comment by gautamsi** [comment]
you can use `appointmentObject.Recurrence instanceof ews.WeeklyPattern` is this is true you can treat this as `WeeklyPattern`

see more example on how to work with recurrence https://msdn.microsoft.com/en-us/library/office/dd633683(v=exchg.80).aspx

**Comment by marcoancona** [comment]
Oh I didn't think I could use the .NET code 1:1... good to know.
One last think, I think there is another problem with parsing the dates withing a recurring pattern when the date format is like `2015-10-15+02:00`.
I see a warning in the console:

```
Deprecation warning: value provided is not in a recognized ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
```
and when I try something like `item.Recurrence.StartDate.Date.toDate()` I get `Invalid date`

**Comment by gautamsi** [comment]
I have to fix conversion of `DateTimeOffset` which is skipped for now.

**Comment by gautamsi** [comment]
you can use .Net code 1:1 in most cases except for the fact it is not synchronous, you have to use `.then()` all the time. if you happen to be TypeScript fan, you can use the code 1:1 using `async` in latest 2.1 beta.

**Comment by marcoancona** [comment]
I see the problem... I was wondering if there is a temporary workaround for this. For example, can I access the raw Exchange XML response for an item property (eg. Recurrence) ? This would allow me to implement a temporary DateTime parser... or one could find workarounds for any type that has not been ported yet.

**Comment by gautamsi** [comment]
I will fix that for you soon.

**Comment by gautamsi** [comment]
I have updated the code, you can fix yours by adding a line in `ExchangeServiceBase.ts` as this
```ts
ConvertStartDateToUnspecifiedDateTime(value: string): DateTime { //should be line 195
value = value.substring(0, 10); 
if (StringHelper.IsNullOrEmpty(value)) { //should be line 197
```
or you can fix ExchangeServiceBase.js in node_modules directory

```js
ExchangeServiceBase.prototype.ConvertStartDateToUnspecifiedDateTime = function (value) { //should be line 117
value = value.substring(0, 10);
```

**Comment by gautamsi** [comment]
Leave a comment

**Comment by marcoancona** [comment]
Sorry for the late feedback. I `gulp build` the current `master`. Looks like there is still a problem with the Recurrence property in case of WeeklyPattern:

```
[RecurrencePropertyDefinition] 		Loading property :		Recurrence
TypeError: Cannot read property 'OnChange' of undefined
    at new WeeklyPattern (/home/anconam/node_modules/ews-javascript-api/js/ComplexProperties/Recurrence/Patterns/Recurrence.WeeklyPattern.js:25:31)
    at Function.RecurrencePropertyDefinition.GetRecurrenceFromString (/home/anconam/node_modules/ews-javascript-api/js/PropertyDefinitions/RecurrencePropertyDefinition.js:61:30)
    at RecurrencePropertyDefinition.LoadPropertyValueFromXmlJsObject (/home/anconam/node_modules/ews-javascript-api/js/PropertyDefinitions/RecurrencePropertyDefinition.js:119:59)
    at PropertyBag.LoadFromXmlJsObject (/home/anconam/node_modules/ews-javascript-api/js/Core/PropertyBag.js:223:53)
    at Appointment.ServiceObject.LoadFromXmlJsObject (/home/anconam/node_modules/ews-javascript-api/js/Core/ServiceObjects/ServiceObject.js:256:26)
    at Function.EwsServiceJsonReader.ReadServiceObjectsCollectionFromJson (/home/anconam/node_modules/ews-javascript-api/js/Core/EwsServiceJsonReader.js:46:39)
    at GetItemResponse.ReadElementsFromXmlJsObject (/home/anconam/node_modules/ews-javascript-api/js/Core/Responses/GetItemResponse.js:41:65)
    at GetItemResponse.ServiceResponse.LoadFromXmlJsObject (/home/anconam/node_modules/ews-javascript-api/js/Core/Responses/ServiceResponse.js:144:22)
    at GetItemRequestForLoad.MultiResponseServiceRequest.ParseResponseXMLJsObject (/home/anconam/node_modules/ews-javascript-api/js/Core/Requests/MultiResponseServiceRequest.js:75:22)
    at GetItemRequestForLoad.MultiResponseServiceRequest.ParseResponse (/home/anconam/node_modules/ews-javascript-api/js/Core/Requests/MultiResponseServiceRequest.js:121:25)
```

**Comment by marcoancona** [comment]
Sorry for the late feedback. The problem seems solved. Planning a release of 0.8.1?

**Comment by gautamsi** [comment]
I have created a beta tag to push changes as soon as done working on. try this  `npm i ews-javascript-api@next` 

will be skipping 0.8.1, this beta/dev tag includes all of 0.8.1 fixes

**Comment by marcoancona** [comment]
Perfect thanks
