### ISSUE TITLE
FindItems with SearchFilter and Extended Property

### ISSUE THREAD

**Issue by demarius** [gautamsi/ews-javascript-api#25]
I'm trying to use `ews.IsEqualTo` as a search filter for a specific message header, with a property definition like this:
```new ews.ExtendedPropertyDefinition(ews.DefaultExtendedPropertySet.InternetHeaders, 'header-name', ews.MapiPropertyType.String)```

When I try to use any filter with FindItems(), I get the following error:
`[Error: SearchFilter.ts - WriteToXml : Not implemented.]`

Bit confusing given that it says here there are some available filters: https://github.com/gautamsi/ews-javascript-api/blob/ae2754284242f5a1756a13d6876bbab942cf9736/src/js/Core/ExchangeService.ts#L827

Am I doing something wrong? Or can nothing happen until SearchFilter.WriteToXml() is implemented?

**Comment by demarius** [comment]
Also, is there anything that can be done about this? http://ews-javascript-api.github.io/api/classes/exchangeservice.html#loadpropertiesforitems

I'm writing a service that uses custom headers for indexing/tracking, I want to be sure I can get my custom headers back. I assumed I'd be okay with something like this: https://msdn.microsoft.com/en-us/library/office/hh545614(v=exchg.140).aspx

**Comment by gautamsi** [comment]
FindItems methods are implemented for the code required to complete this task. not each and everything is available :(. SearchFilters are there but I have to implement search filter syntax. FindItems has other variations which works. 

MimeContent is not implemented yet. 

I will take a look by this weekend.

**Comment by demarius** [comment]
which variation can I use that will get my custom headers back?

**Comment by demarius** [comment]
Thank you for your reply!

**Comment by demarius** [comment]
It occurs to me I should specify, I have to be compatible with Exchange 2007 so I can't use the 2010 queryString overload.

**Comment by gautamsi** [comment]
custom headers will not work as per example in the link you provided.

The library is not 100% complete. stay tuned for custom headers. Will update this issue when complete.

**Comment by gautamsi** [comment]
This will be something I will work over next week.

**Comment by gautamsi** [comment]
can you build it form dev branch and give it a try. SearchFilter should be working now. Could not test due to lack of time, let me know if this works or have any issues. Send example code to test.

MimeType is not ready yet. may be ready in next few days.

**Comment by gautamsi** [comment]
I have pushed updates to dev branch with MapiType. try running it once again

**Comment by gautamsi** [comment]
v0.2.4 published with these changes.

**Comment by demarius** [comment]
Awesome. I will give it a try today.

**Comment by gautamsi** [comment]
get from npm, do not plan to release on github anymore until feature complete.

**Comment by demarius** [comment]
Hey,


I got the latest and things are looking more hopeful. I did notice some strangeness when sending a message with a custom header. Here is a snippet:

```var header_property = new ews.ExtendedPropertyDefinition(
            ews.DefaultExtendedPropertySet.InternetHeaders,
            'x-header-thing',
            ews.MapiPropertyType.String)
   message = new ews.EmailMessage(exch)
   message.SetExtendedProperty(header_property, 'header_value')
   message.SendAndSaveCopy().then(//stuff
```

I get this in the console:
```[PropertyBag.get_this[]] propertyDefinition is marked with AutoInstantiateOnRead but is not a descendant of ComplexPropertyDefinitionBase
[ComplexProperty.Changed] OnChange events not fired due to circular calling, todo: fix needed
[ComplexProperty.Changed] OnChange events not fired due to circular calling, todo: fix needed
[PropertyBag.get_this[]] propertyDefinition is marked with AutoInstantiateOnRead but is not a descendant of ComplexPropertyDefinitionBase
[AttachmentCollection.IOwnedProperty.set_Owner] value is not a descendant of ItemBase
[AttachmentCollection.IOwnedProperty.set_Owner] value is not a descendant of ItemBase
[TypeError: complexProperty.WriteToXml is not a function]```

Confusing, because it looks like you may have already implemented this functionality here:
https://github.com/gautamsi/ews-javascript-api/blob/ae2754284242f5a1756a13d6876bbab942cf9736/src/js/PropertyDefinitions/ComplexPropertyDefinitionBase.ts#L137

Maybe I am using the library wrong, or perhaps another line someplace in the library must be updated to call the correct function? I'm not sure.

**Comment by gautamsi** [comment]
let me test this. there is chance that some subclass is missing this function, or some parameters are incorrect, will try this example and resolve any bugs soon.

**Comment by gautamsi** [comment]
did not receive exact error, can you provide full example?

**Comment by demarius** [comment]
Only thing missing from the above is:

```
message.Body = 'some html body'
message.SetSubject('some subject')
message.Sender = ews@email.com
message.ToRecipients.Add('recipient@email.com')
```

Then I call `SetExtendedProperty` and `SendAndSaveCopy`. The latter returns the above error.

Am I taking the right steps to add a custom header to outgoing mail?

**Comment by demarius** [comment]
After the above fixes, If I use FindItems with a SearchFilter, this prints immediately:

[TypeError: this.GetXmlElementName is not a function]

The request completes, and it fetches some emails and prints them in the console, but `response.items` is empty.

And, hopefully lastly, see this code snippet and error:

```
 var convIndex = new ews.ExtendedPropertyDefinition(ews.EmailMessageSchema.ConversationIndex, ews.MapiPropertyType.Binary)

[ByteArrayPropertyDefinition.Parse] ByteArrayPropertyDefinition needs to be improved
Error: ByteArrayPropertyDefinition: incorrect call of ToString(value): value is undefined
    at ByteArrayPropertyDefinition.ToString (/Users/demi/git/ecma/switchedon/sync/node_modules/ews-javascript-api/js/PropertyDefinitions/ByteArrayPropertyDefinition.js:64:15)
    at ByteArrayPropertyDefinition.TypedPropertyDefinition.toString (/Users/demi/git/ecma/switchedon/sync/node_modules/ews-javascript-api/js/PropertyDefinitions/TypedPropertyDefinition.js:68:21)
    at new ExtendedPropertyDefinition (/Users/demi/git/ecma/switchedon/sync/node_modules/ews-javascript-api/js/PropertyDefinitions/ExtendedPropertyDefinition.js:32:21)
```

**Comment by demarius** [comment]
Also, thanks for helping resolve the outgoing mail issue, it works great now!

**Comment by gautamsi** [comment]
can you provide full example here or gist. I can check and fix remaining bugs.

**Comment by demarius** [comment]
```
var header_property = new ews.ExtendedPropertyDefinition(
  ews.DefaultExtendedPropertySet.InternetHeaders,
  'custom-header-name',
  ews.MapiPropertyType.String),
view = new ews.ItemView(100),
filter = new ews.SearchFilter.PropertyBasedFilter(header_property) //also tried SearchFilter.Exists

exch.FindItems(WellKnownFolderName.Inbox, filter, view).then(function (response) {
  //response is a FindItemsResult obj but response.items is empty
}, function (error) {
  console.log(error) //logs immediately, "[TypeError: this.GetXmlElementName is not a function]"
})
```

I have also tried setting `view.PropertySet = new ews.PropertySet(
 [ews.BasePropertySet.IdOnly, ews.EmailMessageSchema.ConversationIndex,
  ews.EmailMessageSchema.InternetMessageHeaders])`

however I am unsure of the syntax for a custom property set.

**Comment by gautamsi** [comment]
I fixed few bugs. pushed 0.2.5 on npm. it contains few other bug fixes, please update.

for your custom header scenario, test in two steps

1. create email and send it to yourself, so that you have a copy in inbox. (code in TypeScript)
```typescript
import {EwsLogging, ExchangeService, ExchangeCredentials, ExchangeVersion, ExtendedPropertyDefinition, Uri, DefaultExtendedPropertySet, MapiPropertyType, BasePropertySet, PropertySet, SearchFilter, ItemView, WellKnownFolderName, EmailMessage, MessageBody} from "ews-javascript-api";
import credentials = require("./credentials");
var exch = new ExchangeService(ExchangeVersion.Exchange2010);
exch.Credentials = new ExchangeCredentials(credentials.userName, credentials.password);
exch.Url = new Uri("https://outlook.office365.com/Ews/Exchange.asmx");

var header_property = new ExtendedPropertyDefinition(DefaultExtendedPropertySet.InternetHeaders, 'x-header-thing', MapiPropertyType.String)
var message = new EmailMessage(exch)
message.SetExtendedProperty(header_property, 'header_value')
message.Body = new MessageBody('some html body')
message.SetSubject('some subject')
//message.Sender = new EmailAddress("ews@email.com")
message.ToRecipients.Add('ews@email.com')
message.SendAndSaveCopy().then(() => {
    console.log("sent.......");
}, (ei) => {
    console.log(ei.stack, ei.stack.split("\n"));
    console.log("error");
});
```
2. verify that you received message and it has custom header
3. run search query with ews with following code

```typescript
import {EwsLogging, ExchangeService, ExchangeCredentials, ExchangeVersion, ExtendedPropertyDefinition, Uri, DefaultExtendedPropertySet, MapiPropertyType, BasePropertySet, PropertySet, SearchFilter, ItemView, WellKnownFolderName, EmailMessage, MessageBody} from "ews-javascript-api";
import credentials = require("./credentials");
var exch = new ExchangeService(ExchangeVersion.Exchange2010);
exch.Credentials = new ExchangeCredentials(credentials.userName, credentials.password);
exch.Url = new Uri("https://outlook.office365.com/Ews/Exchange.asmx");

var header_property = new ExtendedPropertyDefinition(    DefaultExtendedPropertySet.InternetHeaders,    'x-header-thing',    MapiPropertyType.String)
var header_property2 = new ExtendedPropertyDefinition(    DefaultExtendedPropertySet.InternetHeaders,    'x-header-thing2',    MapiPropertyType.String)

var filter = new SearchFilter.Exists(header_property)
var propertyset = new PropertySet(BasePropertySet.IdOnly,[header_property])
var view = new ItemView(10);
view.PropertySet = propertyset;
exch.FindItems(WellKnownFolderName.Inbox, filter, view).then((response) => {
    EwsLogging.Log(response, true, true);
}, (error) => {
    console.log(error) //logs immediately, "[TypeError: this.GetXmlElementName is not a function]"
})
```

you can change `var propertyset = new PropertySet(BasePropertySet.IdOnly,[header_property])` with `var propertyset = new PropertySet(BasePropertySet.FirstClassProperties,[header_property])` to get All default properties along with your custom property with FindItems. by default, FindItems will not return ExtendedProperties.

**Comment by demarius** [comment]
Thanks! Now I can get my custom headers back from the inbox. I did notice that FindItems is still empty if I try to search the outbox for those same messages. I also still get the error above about the conversationIndex though that should probably be a separate issue.

**Comment by gautamsi** [comment]
how do you get custom headers back without FindItems result? In my test it is working and have no issues. did you pull latest version 0.2.5?

**Comment by demarius** [comment]
The code you have here works fine for inbox but not outbox it seems. I'll generate some more data and try again to be sure.

**Comment by gautamsi** [comment]
there is nothing in outbox, use SentItems.  that works too.

**Comment by demarius** [comment]
That was the trouble. Thank you again!

**Comment by gautamsi** [comment]
glat that it worked, closing this issue.
