### ISSUE TITLE
Can't send HTML through EWS NTLM Connection but sends text fine

### ISSUE THREAD

**Issue by jblaketc** [gautamsi/ews-javascript-api#81]
I managed to send a test email with just text in it. That worked fine. But when I switch to sending basic html, I get this strange error that I'm not sure what to do with:

[MultiResponseServiceRequest.Execute] ServiceErrorHandling.ThrowOnError error handling is only valid for singleton request

Any idea what's failing? I can switch out the html part for just a string and it sends no problem.

This is the code I'm using. I modified the attachment code in the wiki.
````javascript
// exchange server connection info
			var username = 'Domain\\' + this.getParam("EwsUsername");
			var password = this.getParam("EwsPassword");
			var host = this.getParam("EwsUrl");

			// uncomment next line to disable certificate chain test - only for development
	
			process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = '0';

			var ews = require("ews-javascript-api");
			var ntlmXHR = require("./xtlmXHRApi");
			var ntlmXHRApi = new ntlmXHR.ntlmXHRApi(username, password);
			var exch = new ews.ExchangeService(ews.ExchangeVersion.Exchange2010);
			ews.EwsLogging.DebugLogEnabled = true;

			// next line hijacks the XHR request from ews-javascript-api and use ntlmxhrapi
			exch.XHRApi = ntlmXHRApi;

			exch.Credentials = new ews.ExchangeCredentials(username, password); //otherwise error out on null credential
			exch.Url = new ews.Uri(host);

			/*
			 Setup the email
			 */

			var testHtml = `<html>
                  <head>
                  </head>
                  <body>
                    <img width="100" height="100" id="1" src="cid:Party.jpg" />
                  </body>
                </html>`;

			var msgattach = new EmailMessage(exch);
			msgattach.Subject = emailRecord.Subject;
			msgattach.ToRecipients.Add(emailRecord.To);
			msgattach.Body = new MessageBody(BodyType.HTML,testHtml);
			msgattach.Send().then(() => {
				console.log("thoeenhteotheothooeth")
				emailRecord.Status = "Processed";
				emailRecord.save({fields: ['Status']}).then(()=> {
					done();
				}).catch((err)=> {
					done();
				});
			}, (ei) => {
				console.log("ERROR!")
				emailRecord.Status = "Errored";
				emailRecord.save({fields: ['Status']}).then(()=> {
					done(ei);
				}).catch((err)=> {
					done(ei);
				});
			
			});

````

Thanks for the help.

**Comment by gautamsi** [comment]
have you tried pulling latest version, I fixed similar issue in #76  this was supposed to fix all errors of such type.

**Comment by jblaketc** [comment]
Yep, I'm on 0.5.2. Still no go.

This is still valid for the ntlmXHRApi wrapper, correct?

````javascript

//see reference implementation in ews-javascript-api_repo@github\test\MockXHRApi.ts, this one is transpiled JS
var PromiseFactory = require("ews-javascript-api").PromiseFactory;
var httpntlm = require('httpntlm');
var ntlmXHRApi = (function () {
	function ntlmXHRApi(user, password) {
		this.userName = user;
		this.password = password;
	}
	ntlmXHRApi.prototype.xhr = function (xhroptions) {
		var _this = this;
		var userName = _this.userName;
		var domain ='';
		if(userName.indexOf("\\") >= 0){
			var usersplit = userName.split("\\",2);
			userName = usersplit[1];
			domain = usersplit[0];
		}
		var headers = xhroptions.headers;
		
		if(headers["Authorization"]){
			delete headers["Authorization"];
		}
		var xhr = {
			url: xhroptions.url,
			username: userName,
			password: _this.password,
			workstation: '',
			domain: domain,
			body: xhroptions.data ,
			headers: headers
		}
		console.log("DATA", xhroptions.data)
		// no need to use PromiseFactory.create, just return Q promise in your implementation. 
		return PromiseFactory.create(function (successDelegate, errorDelegate, progressDelegate) {
			httpntlm.post(xhr, function (err, res){
				if(err){
					console.log("ERRORR TIME")
					throw err
					errorDelegate(err);
				}
				else{
					//mapping properties to expected return properties.
					res['responseText'] = res.body;
					res['status'] = res.statusCode;
					successDelegate(res);
				}
			});
		});
	};
	Object.defineProperty(ntlmXHRApi.prototype, "type", {
		get: function () {
			return "ntlmXHR";
		},
		enumerable: true,
		configurable: true
	});
	return ntlmXHRApi;
})();
exports.ntlmXHRApi = ntlmXHRApi;

````

**Comment by gautamsi** [comment]
that is correct, let me check the code for EmailMessage.Send again.

**Comment by gautamsi** [comment]
your example works for me without any issue with one change, using escaped html body instead of plain html.

```js
var escape = require('escape-html');
var testHtml = escape(`<html>
                  <head>
                  </head>
                  <body>
                    <img width="100" height="100" id="1" src="cid:Party.jpg" />
                  </body>
                </html>`);
```

**Comment by jblaketc** [comment]
Indeed it does. Thanks alot!
